= Locations in AsciiDoc ASG
Andrew Oberstar <andrew@ajoberstar.org>

I (Andrew Oberstar) am not affiliated with the AsciiDoc working group or any of its projects. However, I am trying to participate as a community member by producing my own implementation of the specification alongside its development in order to support the goal of a final v1 specification.

Where this document refers to the specification's content/goals/intentions, this is purely my interpretation of documents, discussions, and code I have seen and is intended to be representative of the AsciiDoc language project as of specification milestone v0.3.0, TCK milestone v0.1.0, and the parsing lab as of its commit on 2023-08-07.

[NOTE]
====
If I misinterpreted the current position of the AsciiDoc language project anywhere in this document, please let me know of inaccuracies, so I can correct them.
====

== Background

As part of AsciiDoc's specification, an Abstract Semantic Graph (ASG) is being defined to unambiguously represent the parsed structure of an AsciiDoc document. Implementations can optionally include `location` properties on ASG elements to denote the range where the element can be found in the source document.

When an implementation chooses to emit `location` properties in its ASG output, the specification will mandate that they conform to defined location tracking rules so that there is consistency between implementations.

The pre-spec link:https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-tck[asciidoc-tck] and  link:https://github.com/opendevise/asciidoc-parsing-lab/[asciidoc-parsing-lab] have an existing approach that has yet to be formalized in the spec but is being tracked in link:https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-lang/-/issues/48[issue 48].

This document raises questions that the spec's location tracking section should answer to better clarify its goals and behavior and, at the end, my proposal for how locations should be calculated.

== Questions

As part of defining the ASG's location tracking the following questions are important to clearly answer:

. *Purpose/Goals:* What are locations in the ASG in service of? What are the expected use cases and how does the chosen scheme tailor to them?
. *File offsets or not:* Is the included data only line offset and column offset? Or should the file offset  be included as well?
. *Zero-based or one-based:* Should the file/line/column offsets be zero-based or one-based? The answer isn't inherently the same for all 3 elements.
. *Inclusive or exclusive:* Are the start and end positions inclusive or exclusive of the matched characters? Again this may differ between start and end.
. *Special representation:* Does a newline character (or any other character)  have special representation in the format? If so what is the rationale for this, as it implies an exception that must be accounted for by the parser?

== Non-Goals

When I originally raised this topic in link:https://asciidoc.zulipchat.com/#narrow/stream/335219-asciidoc-lang/topic/Locations.20and.20the.20spec[Zulip] I interleaved what are ultimately multiple different issues, so I want to be clear what this _isn't_ about:

* What characters are considered part of any given element. This is not about whether trailing newlines are part of blocks or inlines.
+
For the purpose of this document, presume that an element's bounds are defined elsewhere, but I will include examples of cases where elements begin, contain, or end with newlines and examples without those just to ensure there is clarity of location calculation regardless of the decision on a given element's bounds.
* Which ASG objects should have locations on them. Again, for the purpose of this document, this can be presumed to be defined elsewhere in the spec.
* How locations should be tracked for attribute references or included files. While this would likely be part of a decision record on location tracking, it's not something I'm trying to cover in any way here.

This is purely about calculation of the values in the `location` property presuming those points are decided.

== Terminology

NOTE: This is only meant for clarity of this document and not a presumption of the AsciiDoc project's terminology.

element:: A given syntax component in the language (e.g. paragraph, open block, constrained strong span, etc.)
character:: Any valid Unicode code point
visible character:: Any **character** that is typically displayed in a human-oriented editor (with settings like "visible whitespace" turned off)
newline:: A `\n` **character**, `0A` in Unicode (hexadecimal)
line:: As defined by link:https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206[POSIX]
+
[quote]
____
3.206 Line

A sequence of zero or more non- <newline> characters plus a terminating <newline> character.
____
empty line:: As defined by link:[POSIX]
+
[quote]
____
3.145 Empty Line

A line consisting of only a <newline>; see also Blank Line.
____
position:: A representation of a place within in a file, often used to describe where a *character* or sequence of characters can be found. See *file offset*, *line offset*, *column offset* for concrete ways to talk about a position.
range:: A bounded representation of a sequence of *characters* within a file. Defined by a start and end *position* (both of which must be clarified as inclusive or exclusive). See *location* for a concrete way to talk about a range.
file offset:: A single-integer representation of a *position* within a file. This is independent of *line offset* and *column offset* and identifies a byte or *character* index within the file contents (when thought of as an array or string). File offsets may be 0-based or 1-based. A file offset can independently describe a position.
line offset:: A single-integer representation of the *line* where a *position* can be found. In a zero-based representation, this is the count of *newline* characters preceding the position being described. In one-based, just add 1 to that count. Special character representations may have rules requiring other values for certain characters or positions. A line offset can only fully describe a position with a corresponding *column offset*.
column offset:: A single-integer representation of the column within a *line* where a *position* can be found. In a zero-based representation, this is the count of *characters* that precede the character being described. In one-based, just add 1 to that count. Special character representations may have rules requiring other values for certain characters or positions. A column offset can only fully describe a character's position with a corresponding *line offset*.
location:: The `location` property within the ASG representing a *range* that indicates the bounds of an *element*.
cursor:: An editor's (often visual) current *position* within a file, typically indicating the position where text will be inserted or of the *character* that would be overwritten by the user's next command.
selection:: An editor's (often visual) representation of a *range* that will be acted on by the user's next command.


== Pre-Spec Approach

Pre-spec location tracking is defined in the implementation of the asciidoc-tck and asciidoc-parsing-lab and discussed in the following to issue threads:

* link:https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-lang/-/issues/28#note_1107831[issue 28]
* link:https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-lang/-/issues/48[issue 48]

In terms of answers to the questions listed above:

. **Purpose/Goals:** So far I haven't found a direct articulation of this, but the following are quotes that seemed most informative to me:
+
[quote]
____
When computing the end location of a block, the column of the trailing newline is not included. The block ends at the visible location in the source document, not at the newline that follows it. For a delimited block with a delimiter length of 4, the end column is 4, not 5. There are two reasons for this. First, it points to a column in the source that the cursor can go. Second, it ensures that the end column for a block is consistent regardless of whether it's at the end of the document or somewhere in the middle of it.
____
+
[quote]
____
Normally, the lowest column value is 1. However, there are two cases when the column must be 0. First, if a document has no blocks, then the start and end column is 0. The 0 column indicates that the source does not occupy any space. If the first line of the document is empty, then the start column is 0. The 0 column indicates that there is no content on the first line, only a newline that follows it. Similarly, if the contents of a verbatim block starts with an empty line, then the start column of the content is 0, again indicating that there is no content on the first line, only the newline that follows it. If the content has a trailing empty line, then the end column is 0 for the same reason.
____
+
This suggests to me that the optimization is towards an end user, who may be trying to visually locate the element identified by the ASG location, but I may be misinterpreting.
. **File offsets or not:** Currently, I've seen no proposal that includes a file offset within the `location` property.
. **Zero-based or one-based:** Lines and columns are one-based, with the exception of newlines (see below).
. **Inclusive or exclusive:** Start and end locations are both inclusive.
. **Special handling:** Locations that represent the newline character of an empty line have a column of 0, while in all other cases the first character of a line is considered to have column 1. The stated intent is to communicate that the line contains no visible characters (content).

.Commentary
****
In my attempt at an implementation, special handling of newlines requires an exception in the code to calculate locations. Presuming I'm not mistaken that this is considered "exceptional" or "special" representation, I believe it needs a stronger justification in the specification of the value it provides (and to whom) when weighed against a simpler approach that treats a newline as any other character, just one that is considered the final column in a line.

Again this is purely for calculation of a newlines position, not about whether it is or is not included in the location of any given element.
****

== In the Wild

This section covers how other software calculates and uses positions and ranges.

.Commentary
****
A clear intention in defining a specification is to encourage new and compliant implementations using a variety of technologies to both:

* Further the "reach" of AsciiDoc, making it available in more software than it currently is.
* Ensure that AsciiDoc means AsciiDoc(TM) and not a superficial equivalence like many Markdown flavors have.

This suggests that success of the specification will be a balance between:

* How easy is it for an implementor to interpret and comply with the details of the specification?
* How compatible is the specification with the behavior of the existing Asciidoctor and AsciiDoc.py implementations that have defined the language to date? (i.e. how many documents will "break" when using a spec-compliant implementation)


To further the criteria of "easy to implement", there is clear value in conforming to approaches commonly used in related software in the industry as it will reduce the effort needed to both produce and make use of compliant implementations of AsciiDoc.

An implementor may choose an existing parser library for their implementation or want to hook their implementation up to an editor for navigation, highlighting, or problem reporting and do so with a minimum of effort. This is something I, personally, think is a highly valuable outcome of the specification and should be considered highly in the goals and purpose of location tracking.

While this could lead to an implementation not as obviously clear to a human document author, it is more likely that a document author is a consumer of the implementation's integration with other software than the direct output of the ASG. As such it _is_ human-friendly to be machine-friendly.
****

=== Parsers

==== Peggy.js

link:https://peggyjs.org/[Peggy] is the chosen parser for the reference grammar of AsciiDoc. It includes location tracking as one of its features.

You can see the `peg-test/` folder for a sample of its behavior.

With the grammar:

----
document = blank_line* heading? blank_line* text*
eol = "\n"
title = [a-zA-Z]+
heading = "#"+ " " title eol
text = [a-zA-Z]+ eol
blank_line = eol
----

And the test input:

----
# test

text
----

The following trace output shows what Peggy chose as locations for its matches:

----
{
  type: 'rule.match',
  rule: 'title',
  result: [ 't', 'e', 's', 't' ],
  location: {
    source: undefined,
    start: { offset: 2, line: 1, column: 3 },
    end: { offset: 6, line: 1, column: 7 }
  }
}
{
  type: 'rule.match',
  rule: 'eol',
  result: '\n',
  location: {
    source: undefined,
    start: { offset: 6, line: 1, column: 7 },
    end: { offset: 7, line: 2, column: 1 }
  }
}
{
  type: 'rule.match',
  rule: 'heading',
  result: [ [ '#' ], ' ', [ 't', 'e', 's', 't' ], '\n' ],
  location: {
    source: undefined,
    start: { offset: 0, line: 1, column: 1 },
    end: { offset: 7, line: 2, column: 1 }
  }
}
{
  type: 'rule.match',
  rule: 'eol',
  result: '\n',
  location: {
    source: undefined,
    start: { offset: 7, line: 2, column: 1 },
    end: { offset: 8, line: 3, column: 1 }
  }
}
{
  type: 'rule.match',
  rule: 'eol',
  result: '\n',
  location: {
    source: undefined,
    start: { offset: 12, line: 3, column: 5 },
    end: { offset: 13, line: 4, column: 1 }
  }
}
{
  type: 'rule.match',
  rule: 'text',
  result: [ [ 't', 'e', 'x', 't' ], '\n' ],
  location: {
    source: undefined,
    start: { offset: 8, line: 3, column: 1 },
    end: { offset: 13, line: 4, column: 1 }
  }
}
{
  type: 'rule.match',
  rule: 'document',
  result: [ [], [ [Array], ' ', [Array], '\n' ], [ '\n' ], [ [Array] ] ],
  location: {
    source: undefined,
    start: { offset: 0, line: 1, column: 1 },
    end: { offset: 13, line: 4, column: 1 }
  }
}
----

In response to the questions posed by this document:

* *File offsets or not:* 0-based offsets included
* *Zero-based or one-based*: 0-based file offsets, but 1-based line and column
* *Inclusive or exclusive*: inclusive start, exclusive end
* *Special representation:* appears not, newlines are just another character

==== Antlr



=== Languages

==== Java

For operations within a string:

[source, java]
----
"some text\n\nbelow a line\n".charAt(0); // 's'
"some text\n\nbelow a line\n".charAt(9); // '\n'
"some text\n\nbelow a line\n".charAt(14); // 'o'
"some text\n\nbelow a line\n".substring(5, 11); // 'text\n\n'
----

==== Ruby

For operations within a string:

[source, ruby]
----
"some text\n\nbelow a line\n"[0] # "s"
"some text\n\nbelow a line\n"[9] # "\n"
"some text\n\nbelow a line\n"[14] # "o"
"some text\n\nbelow a line\n".[5..10] # 'text\n\n'
"some text\n\nbelow a line\n".slice(5, 6) # 'text\n\n'
----

==== Common Lisp

For operations within a string:

[source, lisp]
----
CL-USER> (defparameter text (concatenate 'string "some text" (string #\newline) (string #\newline) "below a line" (string #\newline)))
TEXT
CL-USER> text
"some text

below a line
"
CL-USER> (elt text 0)
#\s
CL-USER> (elt text 9)
#\Newline
CL-USER> (elt text 14)
#\o
CL-USER> (subseq text 5 10)
"text
"
----

=== Editors

==== Language Server Protocol

link:https://microsoft.github.io/language-server-protocol/overviews/lsp/overview/[LSP] has become an extremely popular way to increase the reach of languages, by allowing a single LSP server implementation to integrate with any editor that acts as a LSP client. This avoids the MxN combination of integrations that previously needed to exist to support every language in every editor.

===== Positions

LSP defines a link:https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#position[position] as a zero-based place _between_ two characters in a text document. They use the term "character offset" as this document defined *column offset*. They further allow clarification of the "character offset" to count in units defined by UTF-8 (bytes), UTF-16, or UTF-32.

If a provided "character offset" is longer than the line, it is normalized to the line's length.

[quote]
____
Position in a text document expressed as zero-based line and zero-based character offset. A position is between two characters like an ‘insert’ cursor in an editor. Special values like for example -1 to denote the end of a line are not supported.
____

Additionally regarding the variety of end-of-line sequences that could be allowed:

[quote]
____
To ensure that both client and server split the string into the same line representation the protocol specifies the following end-of-line sequences: ‘\n’, ‘\r\n’ and ‘\r’. Positions are line end character agnostic. So you can not specify a position that denotes \r|\n or \n| where | represents the character offset.
____

===== Ranges

LSP defines a link:https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#range[range] as zero-based start (inclusive) and end (exclusive) positions.

[quote]
____
A range in a text document expressed as (zero-based) start and end positions. A range is comparable to a selection in an editor. Therefore, the end position is exclusive. If you want to specify a range that contains a line including the line ending character(s) then use an end position denoting the start of the next line.
____

===== Usage

Many LSP features build off the use of Position and Range, including:

* link:https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEdit[TextEdit] uses a Range and replacement text
* link:https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#location[Location] uses a document URI and a Range
* link:https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#locationLink[LocationLink] uses an origin Range a target document URI, Range, and selection Range.
* link:https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnostic[Diagnostic] uses a Range and metadata about the identified problem

===== Questions

In relation to the questions posed in this document:

* *Purpose/Goals:* not clearly indicated
* *File offsets or not:* not used
* *Zero-based or one-based:* zero-based
* *Inclusive or exclusive:* inclusive start and exclusive end
* *Special representation:* none (explicitly calls out newlines as having no special values)

==== VS Code

===== User-Facing

Visually in VS Code, the following locations are reported in the bottom bar. The `|` character is used to indicate the cursor position. I originally tried to grab screenshots, but had a hard time capturing the blinking cursor.

Cursors are located before a character allowing insertion of text.

.Line 1, Column 1
----
|some text

below a blank line
----

.Line 1, Column 10
----
some text|

below a blank line
----

Given the above cursor location, pressing the right arrow key on the keyboard gives the following position.

.Line 2, Column 1
----
some text
|
below a blank line
----

Pressing right arrow one more time.

.Line 3, Column 1
----
some text

|below a blank line
----

Within a line.

.Line 3, Column 4
----
some text

bel|ow a blank line
----

.Line 3, Column 19
----
some text

below a blank line|
----

===== API

Internally, VS Codes APIs are instead zero-based, but otherwise similar to the visual positions. Given VS Code's heavy association with LSP the overlap of definitions could fairly be considered just one example of behavior in the wild.

* link:https://code.visualstudio.com/api/references/vscode-api#Position[Position] is a zero-based line offset and zero-based character (column) offset as with LSP.
* link:https://code.visualstudio.com/api/references/vscode-api#Selection[Selection] is a range from an anchor position to the active position (active being the position of the cursor).
* link:https://code.visualstudio.com/api/references/vscode-api#Range[Range] is a start and end position.
* link:https://code.visualstudio.com/api/references/vscode-api#Diagnostic[Diagnostic] includes a range and metadata about the problem.

See the `vscode-test/` folder for an example extension that shows some of the values in practice, but as with LSP they highlight selections and ranges having an inclusive start and exclusive end.

===== Questions

In response to the questions posed in this document, see the answers for LSP as nothing seems different here. The only minor exception is that while it's internal API is zero-based like LSP, the visual display of line offset and column offset is one-based.

==== Emacs

===== Positions

* link:https://www.gnu.org/software/emacs/manual/html_node/elisp/Positions.html[Positions]
+
[quote]
____
A position is the index of a character in the text of a buffer. More precisely, a position identifies the place between two characters (or before the first character, or after the last character), so we can speak of the character before or after a given position. However, we often speak of the character “at” a position, meaning the character after that position.

Positions are usually represented as integers starting from 1
____
* link:https://www.gnu.org/software/emacs/manual/html_node/elisp/Point.html[Point] (the cursor)
+
[quote]
____
Point is a special buffer position used by many editing commands, including the self-inserting typed characters and text insertion functions. Other commands move point through the text to allow editing and insertion at different places.

Like other positions, point designates a place between two characters (or before the first character, or after the last character), rather than a particular character. Usually terminals display the cursor over the character that immediately follows point; point is actually before the character on which the cursor sits.

The value of point is a number no less than 1, and no greater than the buffer size plus 1. If narrowing is in effect (see Narrowing), then point is constrained to fall within the accessible portion of the buffer (possibly at one end of it). 
____
* link:https://www.gnu.org/software/emacs/manual/html_node/elisp/Columns.html[Columns]
+
[quote]
____
These functions count each character according to the number of columns it occupies on the screen. This means control characters count as occupying 2 or 4 columns, depending upon the value of ctl-arrow, and tabs count as occupying a number of columns that depends on the value of tab-width and on the column where the tab begins.
____
+
[quote]
____

Function: current-column ¶

    This function returns the horizontal position of point, measured in columns, counting from 0 at the left margin. The column position is the sum of the widths of all the displayed representations of the characters between the start of the current line and point. 
____
+
.Commentary
****
Emacs notably uses visual columns rather than a count of characters in the line. These are also zero-based, while the line offsets and file offsets are one-based.
****

With a similar example to the VS Code one, I use a combination of `M-:` and `(point)` to identify the current location of point in a buffer and `(line-number-mode 1)` `(column-number-mode 1)` to display the line/column in the modeline. As with the VS Code examples `|` will indicate the location of point (the cursor).

.Position 1, Line 1, Column 0
----
|some text

below a blank line
----

.Position 10, Line 1, Column 9
----
some text|

below a blank line
----

Given the above cursor location, pressing `C-f` (the `forward-char` command) on the keyboard gives the following position.

.Position 11, Line 2, Column 0
----
some text
|
below a blank line
----

Pressing `C-f` (the `forward-char` command) one more time.

.Position 12, Line 3, Column 0
----
some text

|below a blank line
----

Within a line.

.Position 15, Line 3, Column 3
----
some text

bel|ow a blank line
----

If you call `(pos-eol)` with the above point location, you get position 30 as you would be moving the point to the end of the line like below.

.Position 30, Line 3, Column 18
----
some text

below a blank line|
----

===== Ranges

* link:https://www.gnu.org/software/emacs/manual/html_node/elisp/The-Mark.html[Mark]
+
[quote]
____
The mark specifies a position to bound a range of text for many commands, such as kill-region and indent-rigidly. These commands typically act on the text between point and the mark, which is called the region.
____
* link:https://www.gnu.org/software/emacs/manual/html_node/elisp/The-Region.html[Region]
+
[quote]
____
The text between point and the mark is known as the region. 
____

The Region is equivalent to the primary Selection in VS Code. `(region-beginning)` and `(region-end)` can be used to identify the positions bounding the region. In the example below, I use two `|` to denote the mark and the point.

.Start Position 6, End Position 11
----
some |text
|
below a blank line
----

If I use `kill-region` to illustrate what's included in the region, you can see that the region start is inclusive and the region end is exclusive.

----
some |
below a blank line
----

===== Navigation

Emacs provides functions like `(goto-char position)` that take a one-based integer position as described above. Along with ones to move a relative number of characters, words, lines, etc.


===== Questions

In response to the questions posed by this document:

* *File offsets or not:* Yes, file offsets are in fact the primary way of finding a position in a document. Navigating to a location by line and column is possible, but requires knowledge of the special handling of columns.
* *Zero-based or one-based:* Mostly one-based, but columns are zero-based.
* *Inclusive or exclusive:* Regions have an inclusive start and exclusive end
* *Special representation:* Newlines don't seem to have any special representation, however tab characters do as defined by `tab-width` which controls the visual number of columns that a tab character takes up.

==== Intellij

===== User-Facing

Visually in Intellij, the following locations are reported in the bottom bar. The `|` character is used to indicate the cursor position. Cursors are located before a character allowing insertion of text.

.Line 1, Column 1
----
|some text

below a blank line
----

.Line 1, Column 10
----
some text|

below a blank line
----

Given the above cursor location, pressing the right arrow key on the keyboard gives the following position.

.Line 2, Column 1
----
some text
|
below a blank line
----

Pressing right arrow one more time.

.Line 3, Column 1
----
some text

|below a blank line
----

Within a line.

.Line 3, Column 4
----
some text

bel|ow a blank line
----

.Line 3, Column 19
----
some text

below a blank line|
----

Selections are visually reported as the cursor location and a count of characters included. In the example below, I use two `|` to denote the mark and the point.

.Line 2, Column 1, 5 characters, 1 line break
----
some |text
|
below a blank line
----

If I use `Cut` to illustrate what's included in the region, you can see that the selection start is inclusive and the region end is exclusive.

----
some |
below a blank line
----

===== API

The Jetbrains API was less clear on definitions compared to VS Code and Emacs, so I'll leave that as an exercise to the reader, but I'd expect some level of consistency with the user-facing results here.

The best hint I found was in link:https://github.com/JetBrains/intellij-community/blob/idea/233.14475.28/platform/core-api/src/com/intellij/lexer/Lexer.java#L82-L90[the Lexer API] which used a single offset, which implied use of file offsets internally.

==== Questions

In response to the questions posed by this doc:

* *File offsets or not:* Some hints that they are used internally
* *Zero-based or one-based:* Visually, Intellij reports one-based line/column offsets
* *Inclusive or exclusive:* inclusive start and exclusive end
* *Special representation:* appears not

==== Vim

NOTE: My Vim knowledge is very minimal, so there may be inaccuracies here.

===== User-Facing

Vim's behavior differs between normal mode and insert mode. The following line and column positions are reported at the bottom.

The unique display when on the newline character of a blank line appears to be described as a "split column" display in link:https://vimhelp.org/usr_03.txt.html#usr_03.txt[the documentation]:

[quote]
____
Sometimes you will see a split column number.  For example, "col 2-9".
This indicates that the cursor is positioned on the second character, but
because character one is a tab, occupying eight spaces worth of columns,
the screen column is 9.
____

.Normal mode and insert mode, Line 1, Column 1
----
|some text

below a blank line
----

.Normal mode, cannot navigate here; Insert mode, Line 1, Column 10
----
some text|

below a blank line
----

.Normal mode, Line 2, Column 0-1; Insert mode, Line 2, Column 1
----
some text
|
below a blank line
----

.Normal mode and insert mode, Line 3, Column 1
----
some text

|below a blank line
----

.Normal mode and insert mode, Line 3, Column 4
----
some text

bel|ow a blank line
----

.Normal mode, cannot navigate here; Insert mode, Line 3, Column 19
----
some text

below a blank line|
----

==== API

* link:https://vimhelp.org/builtin.txt.html#col%28%29[col()] gets the byte index of the given position. The end of the line is count of bytes on the line plus 1. The first character of the column is 1. There are separate functions for visual/screen columns.
* link:https://vimhelp.org/builtin.txt.html#line%28%29[line()] gets the line number of the given position which appears to be 1-based.
* link:https://vimhelp.org/builtin.txt.html#cursor%28%29[cursor()] positions the cursor at a line and column (byte offset)
* link:https://vimhelp.org/builtin.txt.html#getpos%28%29[getpos()] gets a position returning a list of `bufnum` (seems like an indicator of the mark), `lnum` (line number), `cnum` (column = byte offset), `off` (indicating if virtual mode is used or not).

==== Questions

NOTE: I'm not very confident of the answers here, being very unfamiliar with Vimscript, so I couldn't easily test out the API.

In response to the questions posed in this document:

* *File offsets or not:* doesn't seem like it
* *Zero-based or one-based:* one-based
* *Inclusive or exclusive:* I couldn't tell
* *Special representation:* Newlines/tabs, etc seem to get visually indicated in split mode, but internally the byte offset in the line is what gets used. Ultimately, I'd probably say no special representation.

=== Summary

== My Proposal
